from __future__ import annotations

from typing import Any

from core.utils import write_text


def _value(value: Any) -> str:
    if isinstance(value, float):
        return f"{value:.3f}"
    if value is None:
        return "N/A"
    return str(value)


def _quality_rows(quality: dict[str, Any]) -> str:
    rows = ["| Check | Result | Unexpected rows |", "| --- | --- | ---: |"]
    for check in quality.get("checks", []):
        rows.append(
            f"| {check['name']} | {'PASS' if check['success'] else 'FAIL'} | {check['unexpected_count']} |"
        )
    return "\n".join(rows)

def generate_phase1_report(
    report_path,
    source_summary: dict[str, Any],
    metrics: dict[str, Any],
    quality: dict[str, Any],
    freshness: dict[str, Any],
) -> None:
    """Generate a reproducible baseline report from actual pipeline artifacts."""
    text = f"""# Phase 1 — Baseline Pipeline Report

## Source and lineage

| Field | Value |
| --- | --- |
| Source mode | {source_summary.get('mode', 'unknown')} |
| Raw records | {_value(source_summary.get('raw_records'))} |
| Clean records | {_value(source_summary.get('clean_records'))} |
| Embedding model | {source_summary.get('embedding_model', 'unknown')} |
| Collection | {source_summary.get('collection_name', 'unknown')} |

## Baseline RAG metrics

| Metric | Value |
| --- | ---: |
| Samples | {_value(metrics.get('samples'))} |
| Retrieval hit rate | {_value(metrics.get('retrieval_hit_rate'))} |
| Mean token F1 | {_value(metrics.get('mean_token_f1'))} |
| Judge accuracy | {_value(metrics.get('judge_accuracy'))} |
| Mean judge score | {_value(metrics.get('mean_judge_score'))} |

Ragas: `{metrics.get('ragas')}`

## Data quality gate

GX success: **{quality.get('gx_success')}**
Combined quality/freshness success: **{quality.get('success')}**

{_quality_rows(quality)}

## Freshness SLA

| Field | Value |
| --- | --- |
| Latest published | {_value(freshness.get('latest_published'))} |
| Oldest published | {_value(freshness.get('oldest_published'))} |
| Stale rows / total | {_value(freshness.get('stale_rows'))} / {_value(freshness.get('total_rows'))} |
| Stale ratio | {_value(freshness.get('stale_ratio'))} |
| Freshness threshold | {_value(freshness.get('freshness_threshold_days'))} days |
| Is fresh | **{freshness.get('is_fresh')}** |

The metrics in this report are generated by `script/run_phase1.py`; do not edit
them manually. The same test set is reused by the corrupted and repaired flows.
"""
    write_text(report_path, text)


def generate_corruption_report(
    report_path,
    baseline_metrics: dict[str, Any],
    corrupted_metrics: dict[str, Any],
    repaired_metrics: dict[str, Any],
    corrupted_quality: dict[str, Any],
    repaired_quality: dict[str, Any],
    corrupted_freshness: dict[str, Any],
    repaired_freshness: dict[str, Any],
) -> None:
    """Write the required quantitative three-state repair comparison."""
    metric_names = ("retrieval_hit_rate", "mean_token_f1", "judge_accuracy", "mean_judge_score")
    metric_rows = ["| Metric | Baseline | Corrupted | Repaired | Repaired - Baseline |", "| --- | ---: | ---: | ---: | ---: |"]
    for name in metric_names:
        baseline = baseline_metrics.get(name)
        corrupted = corrupted_metrics.get(name)
        repaired = repaired_metrics.get(name)
        delta = repaired - baseline if isinstance(repaired, (int, float)) and isinstance(baseline, (int, float)) else None
        metric_rows.append(f"| {name} | {_value(baseline)} | {_value(corrupted)} | {_value(repaired)} | {_value(delta)} |")

    text = f"""# Corruption and Idempotent Repair Report

## Three-state performance comparison

{chr(10).join(metric_rows)}

## Quality and freshness comparison

| Signal | Baseline | Corrupted | Repaired |
| --- | --- | --- | --- |
| GX quality success | N/A | **{corrupted_quality.get('gx_success')}** | **{repaired_quality.get('gx_success')}** |
| Combined quality/freshness success | N/A | **{corrupted_quality.get('success')}** | **{repaired_quality.get('success')}** |
| Stale rows / total | N/A | {_value(corrupted_freshness.get('stale_rows'))} / {_value(corrupted_freshness.get('total_rows'))} | {_value(repaired_freshness.get('stale_rows'))} / {_value(repaired_freshness.get('total_rows'))} |
| Stale ratio | N/A | {_value(corrupted_freshness.get('stale_ratio'))} | {_value(repaired_freshness.get('stale_ratio'))} |
| Is fresh | N/A | **{corrupted_freshness.get('is_fresh')}** | **{repaired_freshness.get('is_fresh')}** |

## Interpretation

The corrupted state is intentionally built with six logged failure modes: missing
recent records, blank summaries, injected noise, truncated titles, stale dates,
and duplicate rows. The quality gate should reject this state before serving it.
Repair rebuilds the clean dataframe only from preserved raw records, then rebuilds
the index and evaluates the unchanged benchmark. Therefore, repeated repair runs
are idempotent: they overwrite derived artifacts with the same source-derived
baseline state rather than mutating already-corrupted data.
"""
    write_text(report_path, text)
