"""Read-only verification of the CP1–CP6 deliverables generated by the pipeline."""

from __future__ import annotations

from pathlib import Path
import sys

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from core.config import load_settings
from core.utils import read_json


def main() -> None:
    settings = load_settings(PROJECT_ROOT)
    required = [
        settings.paths.raw_api_response,
        settings.paths.raw_records_json,
        settings.paths.clean_csv,
        settings.paths.clean_json,
        settings.paths.eval_testset,
        settings.paths.embeddings_json,
        settings.paths.corrupted_embeddings_json,
        settings.paths.repaired_embeddings_json,
        settings.paths.baseline_quality_report,
        settings.paths.corrupted_quality_report,
        settings.paths.freshness_report,
        settings.paths.baseline_metrics,
        settings.paths.corruption_log,
        settings.paths.corrupted_metrics,
        settings.paths.repaired_metrics,
        settings.paths.baseline_report,
        settings.paths.comparison_report,
    ]
    missing = [str(path.relative_to(PROJECT_ROOT)) for path in required if not path.exists()]
    if missing:
        raise SystemExit(f"Missing required artifacts: {missing}")

    raw_records = read_json(settings.paths.raw_records_json)
    clean = read_json(settings.paths.clean_json)
    test_set = read_json(settings.paths.eval_testset)
    corruption_log = read_json(settings.paths.corruption_log)
    baseline = read_json(settings.paths.baseline_metrics)
    corrupted = read_json(settings.paths.corrupted_metrics)
    repaired = read_json(settings.paths.repaired_metrics)
    baseline_quality = read_json(settings.paths.baseline_quality_report)
    corrupted_quality = read_json(settings.paths.corrupted_quality_report)
    embedding_manifests = {
        "baseline": read_json(settings.paths.embeddings_json),
        "corrupted": read_json(settings.paths.corrupted_embeddings_json),
        "repaired": read_json(settings.paths.repaired_embeddings_json),
    }
    if len(raw_records) != 24 or len(clean) != 24:
        raise SystemExit("Raw and clean artifacts must each contain 24 records.")
    if len(test_set) != 10 or {item["question_type"] for item in test_set} != {
        "summary", "authors", "date", "categories"
    }:
        raise SystemExit("Test set must contain ten questions covering four question types.")
    operations = {item["operation"] for item in corruption_log.get("operations", [])}
    required_operations = {
        "drop_latest_records", "blank_summary", "inject_noise", "truncate_title",
        "stale_date", "duplicate_rows",
    }
    if operations != required_operations:
        raise SystemExit("Corruption log does not contain exactly the six required operations.")
    if not baseline_quality.get("success") or corrupted_quality.get("success"):
        raise SystemExit("Quality gate status does not prove baseline pass and corruption alert.")
    expected_collections = {
        "baseline": settings.baseline_collection_name,
        "corrupted": settings.corrupted_collection_name,
        "repaired": settings.repaired_collection_name,
    }
    for state, manifest in embedding_manifests.items():
        if manifest.get("embedding_model") != settings.embedding_model:
            raise SystemExit(f"{state} index does not declare the required MiniLM model.")
        if manifest.get("embedding_backend") != "sentence-transformers":
            raise SystemExit(f"{state} index was not built with sentence-transformers MiniLM.")
        if manifest.get("collection_name") != expected_collections[state]:
            raise SystemExit(f"{state} manifest targets the wrong Chroma collection.")
    for metric in ("retrieval_hit_rate", "mean_token_f1"):
        if corrupted[metric] >= baseline[metric]:
            raise SystemExit(f"Corruption did not reduce {metric}.")
        if abs(repaired[metric] - baseline[metric]) > 1e-9:
            raise SystemExit(f"Repair did not restore {metric} to the baseline.")
    print("CP1–CP6 artifact verification passed (GX + MiniLM + 3 Chroma collections).")


if __name__ == "__main__":
    main()
